---
title: "Run heritability analyses"
author: "E Schlatter"
date: "10/13/2022"
output: html_document
---

```{r message=FALSE, warning=FALSE}
setwd("C:/Users/eschlatter/Dropbox/coral_h2")
library(tidyverse)
library(MasterBayes) #for pedigree functions
library(MCMCglmm) #for running the model
library(MCMCpack) #for inverse wishart distributions
library(bayesplot) #mcmc_areas plot function
library(gridExtra) #multiple plots per figure
source('analysis/functions.R')
```

## Fluorescence
```{r}
load('C:/Users/eschlatter/Dropbox/coral_h2/analysis/data/fluor.RData')
```

### Red

#### red~animal+sire+dam+rep

```{r,eval=FALSE}
nu = 0.001
p_var = var(fluor$red_rel,na.rm=TRUE) #total phenotypic variance in relative green fluor
prior_mode = p_var/5 #prior mode (5 variance components)
V = ((nu+2)/nu)*prior_mode #prior parameter V (inverse Wishart) for additive genetic effect

prior1_red = list(R=list(V=V,nu=nu),
                    G=list(G1=list(V=V,nu=nu),G2=list(V=V,nu=nu),
                           G3=list(V=V,nu=nu),G4=list(V=V,nu=nu)))

red_fluor_1 <- MCMCglmm(red_rel~1,
                   random=~animal+rep+sire+dam,
                   prior=prior1_red,
                   ginverse=list(animal=Ainv),
                   data=fluor,nitt=100000,burnin=1000,thin=10,verbose=FALSE)

save(red_fluor_1,prior1_red,file='C:/Users/eschlatter/Dropbox/coral_h2/analysis/models/red_fluor_1.RData')
```

```{r}
load('C:/Users/eschlatter/Dropbox/coral_h2/analysis/models/red_fluor_1.RData')

summary(red_fluor_1)
plot(red_fluor_1)

traces <- red_fluor_1$VCV
herit <- traces[,1]/rowSums(traces)
plot(herit)
effectiveSize(herit)
HPDinterval(herit)


Herit <- (traces[,1]+traces[,3]+traces[,4])/rowSums(traces)
plot(Herit)
effectiveSize(Herit)
HPDinterval(Herit)
```

#### red~sire+dam+sire:dam

```{r,eval=FALSE}
# priors aren't specified, but this is the default
nu = 0.0001
V = 1
prior2_red = list(R=list(V=V,nu=nu),
                    G=list(G1=list(V=V,nu=nu),G2=list(V=V,nu=nu),
                           G3=list(V=V,nu=nu)))
# priors look like this
xvals=seq(0,.01,by=0.0001)
plot(xvals,dinvgamma(xvals,shape = nu/2,scale = nu*V/2),type='l')


red_fluor_2=MCMCglmm(red_rel~1,
                     random=~dam+sire+dam:sire,
                     family="gaussian",
                     data=fluor,nitt=100000,burnin=1000,thin=10,verbose=FALSE)
save(red_fluor_2,prior2_red,file='C:/Users/eschlatter/Dropbox/coral_h2/analysis/models/red_fluor_2.RData')
```

```{r}
load('C:/Users/eschlatter/Dropbox/coral_h2/analysis/models/red_fluor_2.RData')

summary(red_fluor_2)
plot(red_fluor_2)

traces <- red_fluor_2$VCV
herit <- 2*traces[,2]/rowSums(traces)
plot(herit)
effectiveSize(herit)
HPDinterval(herit)

Herit <- (traces[,1]+traces[,2]+traces[,3])/rowSums(traces)
plot(Herit)
effectiveSize(Herit)
HPDinterval(Herit)
```


#### red~sire+dam+sire:dam, with priors centered on fraction of total VP

```{r,eval=FALSE}
nu = 0.001
p_var = var(fluor$red_rel,na.rm=TRUE) #total phenotypic variance in relative green fluor
prior_mode = p_var/4 #prior mode (4 variance components)
V = ((nu+2)/nu)*prior_mode #prior parameter V (inverse Wishart) for additive genetic effect
prior3_red = list(R=list(V=V,nu=nu),
                    G=list(G1=list(V=V,nu=nu),G2=list(V=V,nu=nu),
                           G3=list(V=V,nu=nu)))

red_fluor_3=MCMCglmm(red_rel~1,
                     random=~dam+sire+dam:sire,
                     prior=prior3_red,
                     family="gaussian",
                     data=fluor,nitt=100000,burnin=1000,thin=10,verbose=FALSE)
save(red_fluor_3,prior3_red,file='C:/Users/eschlatter/Dropbox/coral_h2/analysis/models/red_fluor_3.RData')
```

```{r}
load('C:/Users/eschlatter/Dropbox/coral_h2/analysis/models/red_fluor_3.RData')

summary(red_fluor_3)
plot(red_fluor_3)

traces <- red_fluor_3$VCV
herit <- 2*traces[,2]/rowSums(traces)
plot(herit)
effectiveSize(herit)
HPDinterval(herit)

Herit <- (traces[,1]+traces[,2]+traces[,3])/rowSums(traces)
plot(Herit)
effectiveSize(Herit)
HPDinterval(Herit)
```

#### red~sire+dam+sire:dam, parameter-expanded

```{r,eval=FALSE}
prior4_red = list(R=list(V=1,nu=0.002),
                         G=list(G1=list(V = 1,nu = 1000, alpha.mu=0, alpha.V=1),
                                G2=list(V = 1,nu = 1000, alpha.mu=0, alpha.V=1),
                                G3=list(V = 1,nu = 1000, alpha.mu=0, alpha.V=1)))

red_fluor_4=MCMCglmm(red_rel~1,
                     random=~dam+sire+dam:sire,
                     prior=prior4_red,
                     family="gaussian",
                     data=fluor,nitt=100000,burnin=1000,thin=10,verbose=FALSE)
save(red_fluor_4,prior4_red,file='C:/Users/eschlatter/Dropbox/coral_h2/analysis/models/red_fluor_4.RData')
```

```{r}
load('C:/Users/eschlatter/Dropbox/coral_h2/analysis/models/red_fluor_4.RData')

summary(red_fluor_4)
plot(red_fluor_4)

traces <- red_fluor_4$VCV
herit <- 2*traces[,2]/rowSums(traces)
plot(herit)
effectiveSize(herit)
HPDinterval(herit)

Herit <- (traces[,1]+traces[,2]+traces[,3])/rowSums(traces)
plot(Herit)
effectiveSize(Herit)
HPDinterval(Herit)
```

#### red~animal+dam+rep
This might make more sense than trying to estimate sire separately from animal, because there's not much replication within sires.
```{r,eval=FALSE}
nu = 0.001
p_var = var(fluor$red_rel,na.rm=TRUE) #total phenotypic variance in relative green fluor
prior_mode = p_var/4 #prior mode (4 variance components)
V = ((nu+2)/nu)*prior_mode #prior parameter V (inverse Wishart) for additive genetic effect

prior5_red = list(R=list(V=V,nu=nu),
                    G=list(G1=list(V=V,nu=nu),G2=list(V=V,nu=nu),
                           G3=list(V=V,nu=nu)))

red_fluor_5 <- MCMCglmm(red_rel~1,
                   random=~animal+dam+rep,
                   prior=prior5_red,
                   ginverse=list(animal=Ainv),
                   data=fluor,nitt=100000,burnin=1000,thin=10,verbose=FALSE)

save(red_fluor_5,prior5_red,file='C:/Users/eschlatter/Dropbox/coral_h2/analysis/models/red_fluor_5.RData')
```

```{r}
load('C:/Users/eschlatter/Dropbox/coral_h2/analysis/models/red_fluor_5.RData')

summary(red_fluor_5)
plot(red_fluor_5)

traces <- red_fluor_5$VCV
dam_trace <- data.frame(time=1:9900,dam=as.data.frame(traces[,2]))
plot(dam_trace,type='l',ylim=c(0,5))
x <- dist(dam_trace$var1)


herit <- traces[,1]/rowSums(traces)
plot(herit)
effectiveSize(herit)
HPDinterval(herit)


Herit <- (traces[,1]+traces[,2])/rowSums(traces)
plot(Herit)
effectiveSize(Herit)
HPDinterval(Herit)
```
